/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.ProviderAdminRole;

import userinterface.SystemAdminWorkArea.*;
import userinterface.RegisterationPanels.*;
import Business.Customer.Customer;
import Business.EcoSystem;
import Business.Employee.Employee;
import Business.Enterprise.Enterprise;
import Business.Enterprise.EnterpriseDirectory;
import Business.Network.Network;
import Business.Organization.LabOrganization;
import Business.Organization.Organization;
import Business.Organization.SysAdmin;
import Business.Role.AdminRole;
import Business.Role.CustomerRole;
import Business.Role.Role;
import Business.UserAccount.UserAccount;
import Business.UserAccount.UserAccountDirectory;
import Business.WorkQueue.AccessApprovalRequest;
import Business.WorkQueue.LabTestWorkRequest;
import Business.WorkQueue.ProviderRegistrationRequest;
import Business.WorkQueue.WorkQueue;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Component;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.showMessageDialog;
import javax.swing.JPanel;
import userinterface.ProviderAdminRole.ProviderWorkAreaJPanel;
import userinterface.SystemAdminWorkArea.SystemAdminWorkAreaJPanel;

/**
 *
 * @author pravinash
 */
public class ReviewRegistrationJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ProviderAdminRegistrationWorkAreaJPanel
     */
    JPanel userProcessContainer;
    EcoSystem system;
    private UserAccount userAccount;
    private UserAccount reviewer;

    public ReviewRegistrationJPanel(JPanel userProcessContainer, EcoSystem system, UserAccount userAccount, UserAccount reviewer) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.system = system;
        this.userAccount = userAccount;
        this.reviewer = reviewer;
        populateRegistration();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        ProviderCityJTxtField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        ProviderAddrJTxtArea = new javax.swing.JTextArea();
        BtnUpdate = new javax.swing.JButton();
        BtnBack = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel10 = new javax.swing.JLabel();
        entTypTxt = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        StatusTxt = new javax.swing.JTextField();
        NetworkTxt = new javax.swing.JTextField();
        SaveBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        ProviderNameJTxtField = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 153, 255), 5));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("Review Registration Request");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(135, 86, -1, -1));

        jLabel3.setText("Address:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(161, 200, -1, -1));

        jLabel4.setText("City:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(191, 292, -1, -1));

        jLabel5.setText("Network:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(159, 343, -1, -1));

        ProviderCityJTxtField.setEditable(false);
        add(ProviderCityJTxtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(298, 289, 203, -1));

        ProviderAddrJTxtArea.setEditable(false);
        ProviderAddrJTxtArea.setColumns(20);
        ProviderAddrJTxtArea.setRows(5);
        jScrollPane1.setViewportView(ProviderAddrJTxtArea);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(298, 200, 200, 71));

        BtnUpdate.setText("Edit Status");
        BtnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnUpdateActionPerformed(evt);
            }
        });
        add(BtnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 400, -1, -1));

        BtnBack.setText("<<Back");
        BtnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBackActionPerformed(evt);
            }
        });
        add(BtnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 410, -1, -1));

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(524, 155, 16, 240));

        jLabel10.setText("Enterprise Type:");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(547, 176, -1, -1));

        entTypTxt.setEditable(false);
        add(entTypTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 173, 184, -1));

        jLabel7.setText("Status:");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(546, 354, 118, -1));

        StatusTxt.setEditable(false);
        add(StatusTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 351, 184, -1));

        NetworkTxt.setEditable(false);
        add(NetworkTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(298, 340, 203, -1));

        SaveBtn.setText("Save");
        SaveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveBtnActionPerformed(evt);
            }
        });
        add(SaveBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 400, -1, -1));

        jLabel2.setText("Name:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(161, 165, 63, 26));

        ProviderNameJTxtField.setEditable(false);
        add(ProviderNameJTxtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(298, 165, 203, -1));
    }// </editor-fold>//GEN-END:initComponents

    public void populateRegistration() {
        ProviderNameJTxtField.setText(userAccount.getEmployee().getName());
        ProviderAddrJTxtArea.setText(userAccount.getEmployee().getEnterpriseAddress());
        ProviderCityJTxtField.setText(userAccount.getEmployee().getEnterpriseCity());
        NetworkTxt.setText(userAccount.getEmployee().getEnterpriseState());
        entTypTxt.setText(userAccount.getEmployee().getType());
        StatusTxt.setText(userAccount.getEmployee().getRegStatus());
    }
    private void BtnBrowseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBrowseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnBrowseActionPerformed

    private void BtnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];

        //        if (component.getName().equals("doctor")) {
            ProviderWorkAreaJPanel providerWorkAreJPanel = (ProviderWorkAreaJPanel) component;
            providerWorkAreJPanel.populateAccessRequestTbl();
            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
            layout.previous(userProcessContainer);
            ////        } else {
            //            SystemAdminWorkAreaJPanel systemAdminWorkAreaJPanel = (SystemAdminWorkAreaJPanel) component;
            //            systemAdminWorkAreaJPanel.populateAccessRequestTbl();
            //            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
            //            layout.previous(userProcessContainer);
            //        }
    }//GEN-LAST:event_BtnBackActionPerformed

    private void BtnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnUpdateActionPerformed
        // TODO add your handling code here:
        StatusTxt.setEditable(true);
        StatusTxt.setBackground(Color.green);
    }//GEN-LAST:event_BtnUpdateActionPerformed

    private void SaveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveBtnActionPerformed
        // TODO add your handling code here:
        userAccount.getEmployee().setRegStatus("Active");
        //        for (UserAccount u : system.getUserAccountDirectory().getUserAccountList()){
            //            if(u.getUsername().equals("sysadmin")){
                //                System.out.println(u.getPassword());
                //                for (WorkRequest wr : u.getWorkQueue().getWorkRequestList()){
                    //                    if(wr.getSender().equals(userAccount)){
                        //                        wr.setStatus(StatusTxt.getText());
                        //                        userAccount.setStatus(StatusTxt.getText());
                        //                    }
                    //                }
                //            }
            //        }
        for (WorkRequest wr : reviewer.getWorkQueue().getWorkRequestList()) {
            if (wr.getSender().equals(userAccount)) {
                wr.setStatus(StatusTxt.getText());
                userAccount.setStatus(StatusTxt.getText());
            }
        }

        JOptionPane.showMessageDialog(null, "Registered Successfully");
        StatusTxt.setEditable(false);
    }//GEN-LAST:event_SaveBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnBack;
    private javax.swing.JButton BtnUpdate;
    private javax.swing.JTextField NetworkTxt;
    private javax.swing.JTextArea ProviderAddrJTxtArea;
    private javax.swing.JTextField ProviderCityJTxtField;
    private javax.swing.JTextField ProviderNameJTxtField;
    private javax.swing.JButton SaveBtn;
    private javax.swing.JTextField StatusTxt;
    private javax.swing.JTextField entTypTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
