/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.RegisterationPanels;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.Organization;
import Business.Organization.OrganizationDirectory;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author hp
 */
public class RegisterDoctor extends javax.swing.JPanel {


    /**
     * Creates new form RegisterMedicalSchool
     */
    JPanel userProcessContainer;
    EcoSystem system;

    public RegisterDoctor(JPanel userProcessContainer, EcoSystem system) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.system = system;
        populateComboBoxProvider();
        populateComboBoxNetwork();
    }

    private void populateComboBoxProvider() {

        registerationSelectionComboBox.removeAllItems();
        for (Enterprise.EnterpriseType protype : Enterprise.EnterpriseType.values()) {
            registerationSelectionComboBox.addItem(protype.toString());
            jComboBox2.removeAllItems();
         
        
        }
        

    }
    private void populateComboBoxNetwork(){
    for (Network network : system.getNetworkList()) {
            jComboBox2.addItem(network.toString());
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        txtFiledFname = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        textFieldLname = new javax.swing.JTextField();
        registerationSelectionComboBox = new javax.swing.JComboBox<>();
        textFieldept = new javax.swing.JTextField();
        txtFieldSSN = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 255, 204), 5));
        setMaximumSize(new java.awt.Dimension(602, 390));
        setPreferredSize(new java.awt.Dimension(550, 390));
        setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 51));
        jLabel1.setText("Doctor Registration");
        add(jLabel1);
        jLabel1.setBounds(300, 40, 244, 36);

        txtFiledFname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFiledFnameActionPerformed(evt);
            }
        });
        add(txtFiledFname);
        txtFiledFname.setBounds(200, 120, 200, 30);

        jLabel2.setText("First Name:");
        add(jLabel2);
        jLabel2.setBounds(120, 120, 90, 20);

        jLabel3.setText("Last Name:");
        add(jLabel3);
        jLabel3.setBounds(410, 120, 70, 20);

        jLabel4.setText("Department: ");
        add(jLabel4);
        jLabel4.setBounds(120, 160, 90, 20);

        jLabel5.setText("SSN:");
        add(jLabel5);
        jLabel5.setBounds(120, 200, 90, 20);
        add(textFieldLname);
        textFieldLname.setBounds(480, 120, 200, 30);

        add(registerationSelectionComboBox);
        registerationSelectionComboBox.setBounds(250, 240, 150, 30);

        textFieldept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldeptActionPerformed(evt);
            }
        });
        add(textFieldept);
        textFieldept.setBounds(200, 160, 200, 30);
        add(txtFieldSSN);
        txtFieldSSN.setBounds(200, 200, 200, 30);

        jLabel6.setText("Region:");
        add(jLabel6);
        jLabel6.setBounds(120, 300, 90, 20);

        jButton1.setText("Register");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1);
        jButton1.setBounds(380, 380, 140, 23);

        add(jComboBox2);
        jComboBox2.setBounds(250, 290, 150, 30);

        jLabel7.setText("Select Provider:");
        add(jLabel7);
        jLabel7.setBounds(120, 240, 90, 20);
    }// </editor-fold>//GEN-END:initComponents

    private void txtFiledFnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFiledFnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFiledFnameActionPerformed

    private void textFieldeptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldeptActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldeptActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String fname = txtFiledFname.getText();
        String lname = textFieldLname.getText();
        String dept = textFieldept.getText();
        String ssn = txtFieldSSN.getText();
      
        if(txtFiledFname.getText().isEmpty() && txtFieldSSN.getText().isEmpty() && textFieldLname.getText().isEmpty() && textFieldept.getText().isEmpty()){
        JOptionPane.showMessageDialog(null, "Please fill mandatory fields");
        }
        else{
        
        JOptionPane.showMessageDialog(null, "Request successfully sent to provider");
        RegisterationSelectionJPanel origin = new RegisterationSelectionJPanel(userProcessContainer, system);
            userProcessContainer.add("Original Panel", origin);
            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
            layout.next(userProcessContainer);
        }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JComboBox<String> registerationSelectionComboBox;
    private javax.swing.JTextField textFieldLname;
    private javax.swing.JTextField textFieldept;
    private javax.swing.JTextField txtFieldSSN;
    private javax.swing.JTextField txtFiledFname;
    // End of variables declaration//GEN-END:variables
}
